# Site settings
title:       Taunton Festival of the Arts
email:       info@tauntonfestival.org.uk
author:      Taunton Festival of the Arts
description: "Taunton Festival of the Arts"
baseurl:     ""
url:         ""
date_format: "%b %-d, %Y"

collections:
    news:
        output: true
        
text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'

# Build settings
markdown:     kramdown
permalink:    pretty
sass:
  compressed: true
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
